---
version: '3.6'

services:
  nginx:
    build:
      context: ./nginx
    expose:
      - 8080
    network_mode: 'host'
    restart: always
    volumes:
      - './run:/var/run'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
  h2o:
    image: lkwg82/h2o-http2-server:v2.2.6
    restart: always
    expose:
      - 8080
    network_mode: 'host'
    volumes:
      - './run:/var/run'
      - './h2o/conf.yml:/home/h2o/h2o.conf'
networks: {}

